### ISSUE TITLE
Cannot reproduce the performance for 1-shot.

### ISSUE THREAD

**Issue by xwjabc** [likesiwell/LGM-Net#1]
I have run the code with the settings:
`python train_meta_matching_network.py --way 5 --shot 1`
However, I can only get:
`Epoch 119: test_loss: 1.0596712412834168, test_accuracy: 0.635`
My environment is:
`Ubuntu 18.04, TensorFlow 1.13, CUDA 10, cuDNN 7.6.0`
I used `./data/preprocess_mini_imagenet.py` to preprocess the data from ImageNet images from [RelationNet](https://github.com/floodsung/LearningToCompare_FSL).

My friend conducts an independent trial, but he also cannot reproduce the results. His log is given below:
`(after epoch 92) Testing: test_loss: 1.09543154716, test_accuracy: 0.620875`
In his settings, the mini-ImageNet dataset is from the pickle file in [Gidariss' repo](https://github.com/gidariss/FewShotWithoutForgetting).

In `./saved_models/LGM-Net_5way1shot.csv`, the ideal 5-way 1-shot test accuracy on mini-ImageNet should be 0.69625 (at epoch 92) and later always above 0.69. Thus, I wonder if there is a mistake in our experiment or the settings (e.g. a special mini-ImageNet dataset or a special version of TensorFlow).

**Comment by likesiwell** [comment]
Nice to receive your feedback.
I collect my mini-ImageNet from Original ImageNet dataset according to the *.csv in ./data/miniImagenet/.
And I preprocess it using ./data/preprocess_mini_imagenet.py.
My environment is:
Linuxmint 17.3, TensorFlow 1.4, CUDA 8, cuDNN 6.
I am not sure if these will have any impact.

**Comment by xwjabc** [comment]
Thank you for your reply! I will try to set up an environment with `TensorFlow 1.4, CUDA 8, cuDNN 6`. However, for the dataset, I wonder if it fine for you to send me a version of the processed mini-ImageNet dataset? My email address is xwjabc@gmail.com. Thank you so much!

**Comment by likesiwell** [comment]
I have sent my processed mini-ImageNet to your gmail. I am also rerunning this code to check if there are any problems. Because I removed some unnecessary codes from my original version code. Maybe it had some minor changes I didn't notice which would have negative impacts on training.

**Comment by xwjabc** [comment]
Thank you for your response! With your processed mini-ImageNet dataset, I can obtain 69.45% at epoch 119.

**Comment by DamonAtSjtu** [comment]
I also cannot reproduce the results in  5way-1shot experiment. I wonder if it's fine for you to send me a version of the processed mini-ImageNet dataset?  My email address is tangqidongsjtu@gmail.com. Thank you so much!

**Comment by nlrahimi** [comment]
Hello,

Thanks for the code and comments. 

I have the same problem running the experiment with the version of mini-imagenet I have and would appreciate if you send me the version that worked for you. my email:[neela.rahimi@gmail.com](url)
Thank you so much in advance.
