### ISSUE TITLE
How long it would take to train this model?

### ISSUE THREAD

**Issue by usamieiji** [likesiwell/LGM-Net#2]
I have run the code and found that it would take 12 hours to train 14 epochs on NVIDIA GTX 1080 Ti. Is there anything wrong? Or it would take a long time to train this model indeed.

**Comment by likesiwell** [comment]
Right. It takes about 40 hours to train 60 epochs on 1080Ti in my experiment setting.

**Comment by usamieiji** [comment]
Alright. Thanks for your reply
