### ISSUE TITLE
Consume CPU resources...

### ISSUE THREAD

**Issue by haolsun** [likesiwell/LGM-Net#3]
Hi there,
The program consumes most of the CPU resources but the GPU is rarely used. Also, it occupies the GPU memory. Is that correct?

**Comment by likesiwell** [comment]
I think if you are training with GPU mode,  it would not occupy too much CPU resources.

**Comment by haolsun** [comment]
I think the data_preprocessing in the func 'get_batch' consumes lots of CPU resources.
